#!/bin/bash

CONFIG_PATH=/var/cache/openkeeper
ppp_if=ppp0

echo "openkeeper-cli v4.x"

if [ "0" != "$UID" ] ; then
	echo "需要 root 权限!"
	exit 1
fi

if [ ! -d $CONFIG_PATH ] ; then
	echo "首次使用，调用 ok-config 命令进行配置，若配置错误将无法登录"
	ok-config
fi

eth_if=`cat $CONFIG_PATH/eth`
username=`cat $CONFIG_PATH/user`
password=`cat $CONFIG_PATH/pass`

ok-stop > /dev/null 2>&1
sleep 1
dialnetkeeper "$eth_if" "$username" "$password"

ppp_ip=`ip a show dev $ppp_if | awk '/inet [12]/{print $2}'`
if [ -n "$ppp_ip" ] ; then
	echo "登录成功!"
else
	echo "拨号失败！"
	echo "请检查账户时间，账户密码，网卡等配置"
	exit 1
fi

eth_ip=`ip a show dev $eth_if | awk '/inet [12]/{print $2}'`
eth_ip=`echo $eth_ip | awk -F '/' '{print $1}'`
echo "内网IP:$eth_ip"

if [ "cqupt" == "$(echo $username | awk -F '@' '{print $2}')" ] ; then
	gateway_ip=`ip r | awk '/default via/&&/dev '"$eth_if"'/{print $3}'`
	if [ -n "$gateway_ip" ] ; then
		ip route del default
		ip route del 172.0.0.0/8 > /dev/null 2>&1
		ip route del 202.202.0.0/16 > /dev/null 2>&1

		ip route add 172.16.0.0/12 via $gateway_ip > /dev/null 2>&1
		ip route add 172.32.0.0/16 via $gateway_ip > /dev/null 2>&1
		ip route add 172.33.0.0/16 via $gateway_ip > /dev/null 2>&1
		ip route add 172.34.0.0/16 via $gateway_ip > /dev/null 2>&1
		ip route add 202.202.32.0/20 via $gateway_ip > /dev/null 2>&1
		ip route add 202.202.43.0/24 via $gateway_ip > /dev/null 2>&1
		ip route add 202.202.45.0/24 via $gateway_ip > /dev/null 2>&1
		ip route add 222.177.140.0/24 via $gateway_ip > /dev/null 2>&1
	fi
else
	echo "非重邮学校可以根据相应内网情况自行添加内网路由。"
fi

ip route add default dev $ppp_if > /dev/null 2>&1

# ## 添加6TO4隧道
# ip tunnel add tun6to4 mode sit ttl 64 remote any local $ppp_ip
# ip link set dev tun6to4 up
# ## 添加IPv6地址
# ipv6_ip_p1=`echo $ppp_ip | awk -F'.' '{if ($1>16) {printf("%x",$1)} else {printf("0%x",$1)}}'`
# ipv6_ip_p2=`echo $ppp_ip | awk -F'.' '{if ($2>16) {printf("%x",$2)} else {printf("0%x",$2)}}'`
# ipv6_ip_p3=`echo $ppp_ip | awk -F'.' '{if ($3>16) {printf("%x",$3)} else {printf("0%x",$3)}}'`
# ipv6_ip_p4=`echo $ppp_ip | awk -F'.' '{if ($4>16) {printf("%x",$4)} else {printf("0%x",$4)}}'`
# ipv6_ip=2002:$ipv6_ip_p1$ipv6_ip_p2:$ipv6_ip_p3$ipv6_ip_p4::$ipv6_ip_p1$ipv6_ip_p2:$ipv6_ip_p3$ipv6_ip_p4
# ip -6 addr add $ipv6_ip/16 dev tun6to4
# echo "IPV6:$ipv6_ip"
# ip -6 route add default via ::192.88.99.1 dev tun6to4 metric 1

echo "拨号结束，若关闭本终端，不会断开网络连接，断开网络连接请使用 ok-stop 命令"
echo "处理完毕，若要使用其他账户登录，请用 ok-config 重新配置"

exit 0
